name: logic
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/shd101wyy/logic.dart
author: Yiyi Wang <shd101wyy@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
#  path: ^1.4.1
  built_collection: ^4.2.2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
